### ISSUE TITLE
如何知道它是否已被激活？

### ISSUE THREAD

**Issue by anburocky3** [chengazhen/gitlens-pro#1]

**Comment by chengazhen** [comment]
打开编辑器查看
![image](https://github.com/user-attachments/assets/e24b2440-7d13-40cf-90d0-4c94051e13dc)

**Comment by anburocky3** [comment]
这是否意味着我们可以使用更多天数来激活专业版？

![image](https://github.com/user-attachments/assets/1c03d583-fc63-4d96-a652-8da4f0a3fc35)

**Comment by chengazhen** [comment]
建议你使用 15.1.0 版本

**Comment by anburocky3** [comment]
> 建议你使用 15.1.0 版本
哦，在 16.1.0+ 上不起作用吗？

**Comment by chengazhen** [comment]
在16.0.5起作用，gitlens 一直在更新

**Comment by anburocky3** [comment]
好的，谢谢，我通常不使用它。以后会检查一下。谢谢。制作更多这样的脚本。
